# Generated by Django 4.0.1 on 2022-01-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('color', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('photo_url', models.CharField(max_length=200)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
