# Generated by Django 3.2.8 on 2022-03-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Russia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('photo_file', models.CharField(max_length=200)),
                ('video_url', models.CharField(max_length=200)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'russia',
            },
        ),
    ]
